export const memoryData =[
  {
    username: "Perry",
    shareStatus: "public",
    date: "November 3, 2017",
    content: "Thor: Ragnarok",
    link: "https://marvel.com/movies/movie/222/thor_ragnarok",
    image: "https://www.bleedingcool.com/wp-content/uploads/2017/08/DH_uCKMV0AI_dbF-1.jpg",
  },
  {
    username: "Jeff",
    shareStatus: "public",
    date: "July 6, 2018",
    content: "Ant-Man and the Wasp",
    link: "https://marvel.com/movies/movie/245/ant-man_and_the_wasp",
    image: "https://images-na.ssl-images-amazon.com/images/M/MV5BMDA2MWUzMDQtNzU0Yi00MTAwLWEzZTMtMjA2MjQ5Y2IyMWVhXkEyXkFqcGdeQXVyNDQxNjcxNQ@@._V1_.jpg",
  },
  {
    username: "Jennifer",
    shareStatus: "public",
    date: "May 3, 2019",
    content: "Avengers: Infinity War Part 2",
    link: "https://marvel.com/movies/movie/226/avengers_infinity_war_part_2",
    image: "https://i.kinja-img.com/gawker-media/image/upload/s--GUW9WsSv--/c_scale,f_auto,fl_progressive,q_80,w_800/a9ls8ayqjd75urynoa90.jpg",
  },
  {
    username: "Kim",
    shareStatus: "public",
    date: "March 8, 2019",
    content: "Captain Marvel",
    link: "https://marvel.com/movies/movie/225/captain_marvel",
    image: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ3MjIyMDQxOF5BMl5BanBnXkFtZTgwNDIxNTM2OTE@._V1_.jpg",
  },
  {
    username: "Adam",
    shareStatus: "public",
    date: "February 16, 2018",
    content: "Black Panther",
    link: "https://marvel.com/movies/movie/224/black_panther",
    image: "https://images-na.ssl-images-amazon.com/images/M/MV5BMjQ1MDYzMTM2OV5BMl5BanBnXkFtZTgwODYzODg5MjI@._V1_SY1000_CR0,0,674,1000_AL_.jpg",
  },
  {
    username: "Jennifer",
    shareStatus: "public",
    date: "May 4, 2018",
    content: "Avengers: Infinity War",
    link: "https://marvel.com/movies/movie/223/avengers_infinity_war",
    image: "https://images-na.ssl-images-amazon.com/images/M/MV5BOGQ5NTY3NjktYjIzNS00Y2ZjLWIyODQtMjQzYzg1ZTMzOGI5XkEyXkFqcGdeQXVyNDMwMzEyNzA@._V1_.jpg",
  },
  {
    username: "Brian",
    shareStatus: "public",
    date: "October 17, 2017",
    content: "Spider-Man: Homecoming",
    link: "https://marvel.com/movies/movie/242/spider-man_homecoming",
    image: "https://images-na.ssl-images-amazon.com/images/M/MV5BNTk4ODQ1MzgzNl5BMl5BanBnXkFtZTgwMTMyMzM4MTI@._V1_SY1000_CR0,0,658,1000_AL_.jpg",
  },
  {
    username: "Franie",
    shareStatus: "public",
    date: "August 8, 2017",
    content: "Guardians of the Galaxy Vol. 2",
    link: "https://marvel.com/movies/movie/221/guardians_of_the_galaxy_vol_2",
    image: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg2MzI1MTg3OF5BMl5BanBnXkFtZTgwNTU3NDA2MTI@._V1_SY1000_CR0,0,674,1000_AL_.jpg",
  },
  {
    username: "Perry",
    shareStatus: "public",
    date: "November 4, 2016",
    content: "Doctor Strange",
    link: "https://marvel.com/movies/movie/220/doctor_strange",
    image: "https://images-na.ssl-images-amazon.com/images/M/MV5BNjgwNzAzNjk1Nl5BMl5BanBnXkFtZTgwMzQ2NjI1OTE@._V1_SY1000_CR0,0,674,1000_AL_.jpg",
  },
  {
    username: "Samantha",
    shareStatus: "public",
    date: "May 6, 2016",
    content: "Captain America: Civil War",
    link: "https://marvel.com/movies/movie/219/captain_america_civil_war",
    image: "https://images-na.ssl-images-amazon.com/images/M/MV5BMjQ0MTgyNjAxMV5BMl5BanBnXkFtZTgwNjUzMDkyODE@._V1_SY1000_CR0,0,674,1000_AL_.jpg",
  },
  {
    username: "Jeff",
    shareStatus: "public",
    date: "July 17, 2015",
    content: "Ant-Man",
    link: "https://marvel.com/movies/movie/180/ant-man",
    image: "https://images-na.ssl-images-amazon.com/images/M/MV5BMjM2NTQ5Mzc2M15BMl5BanBnXkFtZTgwNTcxMDI2NTE@._V1_.jpg",
  },
  {
    username: "Jennifer",
    shareStatus: "public",
    date: "May 1, 2015",
    content: "Avengers: Age of Ultron",
    link: "https://marvel.com/movies/movie/193/avengers_age_of_ultron",
    image: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTM4OGJmNWMtOTM4Ni00NTE3LTg3MDItZmQxYjc4N2JhNmUxXkEyXkFqcGdeQXVyNTgzMDMzMTg@._V1_SY1000_SX675_AL_.jpg",
  },
  {
    username: "Franie",
    shareStatus: "public",
    date: "August 1, 2014",
    content: "Guardians of the Galaxy",
    link: "https://marvel.com/movies/movie/179/guardians_of_the_galaxy",
    image: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTAwMjU5OTgxNjZeQTJeQWpwZ15BbWU4MDUxNDYxODEx._V1_SY1000_CR0,0,674,1000_AL_.jpg",
  },
  {
    username: "Samantha",
    shareStatus: "public",
    date: "April 4, 2014",
    content: "Captain America: The Winter Solder",
    link: "https://marvel.com/movies/movie/181/captain_america_the_winter_soldier",
    image: "https://images-na.ssl-images-amazon.com/images/M/MV5BMjM2NzUzNzQwNl5BMl5BanBnXkFtZTgwMDQ1MDkwMTE@._V1_SY1000_CR0,0,674,1000_AL_.jpg",
  },
  {
    username: "Perry",
    shareStatus: "public",
    date: "November 8, 2013",
    content: "Thor: The Dark World",
    link: "https://marvel.com/movies/movie/182/thor_the_dark_world",
    image: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQyNzAwOTUxOF5BMl5BanBnXkFtZTcwMTE0OTc5OQ@@._V1_SY1000_SX700_AL_.jpg",
  },
  {
    username: "Robert",
    shareStatus: "public",
    date: "May 3, 2013",
    content: "Iron Man 3",
    link: "https://marvel.com/movies/movie/176/iron_man_3",
    image: "https://images-na.ssl-images-amazon.com/images/M/MV5BMzgxODgyMzgxMF5BMl5BanBnXkFtZTcwOTg2NzAyOQ@@._V1_SY1000_SX700_AL_.jpg",
  },
  {
    username: "Jennifer",
    shareStatus: "public",
    date: "May 4, 2012",
    content: "Marvel's The Avengers",
    link: "https://marvel.com/movies/movie/152/marvels_the_avengers",
    image: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTk2NTI1MTU4N15BMl5BanBnXkFtZTcwODg0OTY0Nw@@._V1_SY1000_CR0,0,675,1000_AL_.jpg",
  },
  {
    username: "Samantha",
    shareStatus: "public",
    date: "July 22, 2011",
    content: "Captain America: The First Avenger",
    link: "https://marvel.com/movies/movie/125/captain_america_the_first_avenger",
    image: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTYzOTc2NzU3N15BMl5BanBnXkFtZTcwNjY3MDE3NQ@@._V1_SY1000_CR0,0,640,1000_AL_.jpg",
  },
  {
    username: "Perry",
    shareStatus: "public",
    date: "May 6, 2011",
    content: "Thor",
    link: "https://marvel.com/movies/movie/36/thor",
    image: "https://images-na.ssl-images-amazon.com/images/M/MV5BOGE4NzU1YTAtNzA3Mi00ZTA2LTg2YmYtMDJmMThiMjlkYjg2XkEyXkFqcGdeQXVyNTgzMDMzMTg@._V1_SY1000_CR0,0,674,1000_AL_.jpg",
  },
  {
    username: "Robert",
    shareStatus: "public",
    date: "May 7, 2010",
    content: "Iron Man 2",
    link: "https://marvel.com/movies/movie/130/iron_man_2",
    image: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTI4MzU4MzIwMl5BMl5BanBnXkFtZTcwMzIxMTgyMw@@._V1_.jpg",
  },
  {
    username: "Bruce",
    shareStatus: "public",
    date: "Jun 13, 2008",
    content: "The Incredible Hulk",
    link: "https://marvel.com/movies/movie/23/the_incredible_hulk",
    image: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTUyNzk3MjA1OF5BMl5BanBnXkFtZTcwMTE1Njg2MQ@@._V1_SY1000_CR0,0,674,1000_AL_.jpg",
  },
  {
    username: "Robert",
    shareStatus: "public",
    date: "May 2, 2008",
    content: "Iron Man",
    link: "https://marvel.com/movies/movie/19/iron_man",
    image: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_SY1000_CR0,0,674,1000_AL_.jpg",
  }
]

export default memoryData;